#!/bin/sh
build_type=$1
[ "$build_type" ] || build_type="Release"
echo "Using CMAKE_BUILD_TYPE $build_type"

cmake . -B bin -DCMAKE_TOOLCHAIN_FILE=bin/conan_toolchain.cmake -DCMAKE_BUILD_TYPE=$build_type &&
  cp bin/compile_commands.json . &&
  cmake --build bin
